version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-restful-api
    container_name: laravel-restful-api-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/laravel-restful-api/
    volumes:
      - ./:/var/www/laravel-restful-api/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - restful-api-network

  webserver:
    image: nginx:alpine
    container_name: laravel-restful-api-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "9001:8080"
    volumes:
      - ./:/var/www/laravel-restful-api/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - restful-api-network

  db:
    image: mysql:5.7.32
    container_name: laravel-restful-api-db
    restart: unless-stopped
    tty: true
    ports:
      - "3367:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_HOST: '%'
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - restful-api-network

networks:
  restful-api-network:
    driver: bridge

volumes:
  dbdata:
    driver: local